# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "greet",
    srcs = ["greet.cc"],
    hdrs = ["greet.h"],
    includes = ["."],
    visibility = ["//visibility:public"],

)