name: Greetings

on: [push]

jobs:
  greeting:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build repository
      working-directory: ./esib
      run: bazel build //testing:hello_test
    - name: Running test
      working-directory: ./esib
      run: bazel test //testing:hello_test
